[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/google/go-github"
  version = "17.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-license-detector.v2"
  version = "2.0.0"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"
